// This file is auto-generated by Payload but must exist for the admin panel to build.
// Run `pnpm payload generate:importmap` (or `npm run payload generate:importmap`) to regenerate.
export const importMap = {}
